#define LOUPE_PLUGINS_RELATIVE_PATH "@LOUPE_PLUGINS_RELATIVE_PATH@"
#define LOUPE_TRANSLATIONS_RELATIVE_PATH "@LOUPE_TRANSLATIONS_RELATIVE_PATH@"
#cmakedefine01 LOUPE_ENABLE_SENTRY
#if LOUPE_ENABLE_SENTRY
#define LOUPE_SENTRY_DSN "@LOUPE_SENTRY_DSN@"
#endif
