#define PDF4QT_PLUGINS_RELATIVE_PATH "@PDF4QT_PLUGINS_RELATIVE_PATH@"
#define PDF4QT_TRANSLATIONS_RELATIVE_PATH "@PDF4QT_TRANSLATIONS_RELATIVE_PATH@"
#cmakedefine01 PDF4QT_ENABLE_SENTRY
#if PDF4QT_ENABLE_SENTRY
#define PDF4QT_SENTRY_DSN "@PDF4QT_SENTRY_DSN@"
#endif
