#define LOOP_PLUGINS_RELATIVE_PATH "@LOOP_PLUGINS_RELATIVE_PATH@"
#define LOOP_TRANSLATIONS_RELATIVE_PATH "@LOOP_TRANSLATIONS_RELATIVE_PATH@"
#cmakedefine01 LOOP_ENABLE_SENTRY
#if LOOP_ENABLE_SENTRY
#define LOOP_SENTRY_DSN "@LOOP_SENTRY_DSN@"
#endif
