#!/usr/bin/env python3
"""Generate original, deterministic MIT-licensed operator learning PDFs."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
DESTINATION = ROOT / "LoopEditor/operator/samples"


def pdf(bleed: bool, rgb_image: bool = False, unsupported_claim: bool = False, artwork: bool = True) -> bytes:
    boxes = "/MediaBox [0 0 220 220] /TrimBox [10 10 210 210] /BleedBox [0 0 220 220]" if bleed else "/MediaBox [0 0 200 200]"
    content = b"0 g 20 20 180 180 re f\n" if artwork else b""
    resources = "<< >>"
    if rgb_image:
        resources = "<< /XObject << /Image 5 0 R >> >>"
        content += b"q 30 0 0 30 70 70 cm /Image Do Q\n"
    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        f"<< /Type /Page /Parent 2 0 R {boxes}{f' /Resources {resources} /Contents 4 0 R' if artwork else ''} >>".encode(),
    ]
    if artwork:
        objects.append(f"<< /Length {len(content)} >>\nstream\n".encode() + content + b"endstream")
    if rgb_image:
        objects.append(b"<< /Type /XObject /Subtype /Image /Width 1 /Height 1 /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /ASCIIHexDecode /Length 7 >>\nstream\nFF0000>\nendstream")
    if unsupported_claim:
        objects.append(b"<< /GTS_PDFXVersion (PDF/X-5n) >>")
    result = bytearray(b"%PDF-1.7\n% Loop original operator sample\n")
    offsets = [0]
    for index, value in enumerate(objects, 1):
        offsets.append(len(result))
        result.extend(f"{index} 0 obj\n".encode() + value + b"\nendobj\n")
    xref = len(result)
    result.extend(f"xref\n0 {len(offsets)}\n0000000000 65535 f \n".encode())
    for offset in offsets[1:]:
        result.extend(f"{offset:010d} 00000 n \n".encode())
    info = " /Info 5 0 R" if unsupported_claim else ""
    result.extend(f"trailer\n<< /Size {len(offsets)} /Root 1 0 R{info} >>\nstartxref\n{xref}\n%%EOF\n".encode())
    return bytes(result)


def generated_files() -> dict[str, bytes]:
    default = json.loads((ROOT / "loop-preflight/profiles/loop-default.json").read_text(encoding="utf-8"))
    incomplete = json.loads(json.dumps(default))
    incomplete.pop("digest")
    incomplete.update(id="loop-learning-limits", name="Learning: unsupported claim", description="Learning profile: inspect the sample's unsupported PDF/X-5n declaration. This sample does not conform to PDF/X.")
    incomplete["checks"].append({"id": "conformance-claims", "severity": "warning"})
    recipe = {"schema": "loop-action-list/2", "id": "loop-learning-bleed", "name": "Learning: add bleed",
              "steps": [{"id": "bleed", "operation": "add-bleed", "params": {"bleed_mm": 3, "mode": "mirror", "force": True}}]}
    files = {"pass.pdf": pdf(True), "fail.pdf": pdf(True, True), "incomplete.pdf": pdf(True, unsupported_claim=True), "correction.pdf": pdf(False, artwork=False),
             "profile.json": (json.dumps(default, indent=2) + "\n").encode(),
             "incomplete-profile.json": (json.dumps(incomplete, indent=2) + "\n").encode(),
             "correction-recipe.json": (json.dumps(recipe, indent=2) + "\n").encode()}
    files["LICENSE.txt"] = (DESTINATION / "LICENSE.txt").read_bytes()
    jobs = []
    for job_id, title, expected, description in (
        ("pass", "A clear inspection", "pass", "Enabled default checks pass. This is not a formal GWG conformance certificate."),
        ("fail", "A colour finding", "fail", "A synthetic red RGB image is outside the profile's allowed colour spaces. Inspect its finding and limitations."),
        ("incomplete", "An unsupported declaration", "incomplete", "This sample declares unsupported PDF/X-5n and does not conform to PDF/X. Its learning profile inspects conformance claims. Incomplete is not clear; supported checks cannot certify that declaration."),
        ("correction", "Review a blank-page bleed correction", "fail", "This blank page is missing bleed. Plan the imported add-bleed recipe, review and approve it, then read Core's recheck and sign-off. This geometry exercise cannot prove production artwork bleed."),
    ):
        members = {"pdf": f"{job_id}.pdf", "profile": "incomplete-profile.json" if job_id == "incomplete" else "profile.json", "license": "LICENSE.txt"}
        if job_id == "correction":
            members["recipe"] = "correction-recipe.json"
        jobs.append({"id": job_id, "title": title, "expected": expected, "description": description, "members": members})
    manifest = {"license": "MIT", "fixture_class": "development", "provenance": "Original geometric artwork and synthetic RGB pixel generated by scripts/ci/generate_operator_samples.py; no third-party artwork, text, fonts or images.",
                "jobs": jobs, "sha256": {name: hashlib.sha256(data).hexdigest() for name, data in files.items()}}
    files["manifest.json"] = (json.dumps(manifest, indent=2, sort_keys=True) + "\n").encode()
    return files


def main() -> None:
    DESTINATION.mkdir(parents=True, exist_ok=True)
    for name, data in generated_files().items():
        (DESTINATION / name).write_bytes(data)


if __name__ == "__main__":
    main()
