// MIT License
//
// Copyright (c) 2018-2025 Jakub Melka and Contributors
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// gh-243: a committed corpus of synthetic adversarial PDF fixtures, one per
// pdf::PDFProcessingBudget dimension named in the issue, generated by
// scripts/resource_envelope/budget_exhaustion_corpus.py and driven from the
// manifest it writes alongside them
// (UnitTests/testdata/budget_exhaustion/manifest.json). This is the
// adversarial complement to the individual-API-call coverage in
// tst_budgetexhaustiontest.cpp: here, a real (if tiny) PDF file is read
// through pdf::PDFDocumentReader and pdf::PreflightEngine, the way a hostile
// upload actually would be, and every case asserts the run terminates within
// a bounded time and fails closed with the exact exceeded budget attributed
// -- never a hang, a crash, or a silent clean result.
//
// Manifest cases come in two shapes ("path" field):
//  - "session": the fixture is a fully valid, readable document. The budget
//    trips while pdf::PreflightEngine walks it with one pdf::PDFProcessingLimits
//    field (or, for the raster-probe fixture, one preflight check parameter)
//    tightened past what the fixture's shape demands. The structured
//    checks[].budget.{kind,pool,limit,attempted} fields
//    (docs/RESOURCE_BUDGETS.md) are asserted directly.
//  - "reader": the budget trips inside pdf::PDFDocumentReader itself, before
//    a document exists (deep PDF object nesting, a pathological object
//    count). pdf::PDFDocumentReader does not expose the structured
//    pdf::PDFBudgetExceeded detail on failure, only its formatted message, so
//    these cases parse the kind name and the "attempted N, limit M" numbers
//    out of getErrorMessage() (see PDFBudgetExceededException's constructor
//    in pdfprocessingbudget.cpp for the exact format).

#include "pdfdocumentreader.h"
#include "pdfdocumentsession.h"
#include "pdfpreflightverdict.h"
#include "pdfprocessingbudget.h"
#include "preflightengine.h"

#include <QDir>
#include <QElapsedTimer>
#include <QFile>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QRegularExpression>
#include <QSet>
#include <QtTest>

namespace
{

// A generous ceiling: every fixture is deliberately tiny and trips its
// tightened budget almost immediately. This bounds catastrophic regressions
// (a hang, an accidental unbounded loop) without being a tight perf assertion.
constexpr int BOUNDED_MS = 20000;

QString corpusDir()
{
    return QStringLiteral(BUDGET_CORPUS_DIR);
}

pdf::PDFProcessingLimits limitsFromOverrides(const QJsonObject& overrides)
{
    pdf::PDFProcessingLimits limits = pdf::PDFProcessingLimits::conservativeDefaults();
    if (overrides.contains(QStringLiteral("maxDecompressionRatio")))
    {
        limits.maxDecompressionRatio = static_cast<std::int64_t>(overrides.value(QStringLiteral("maxDecompressionRatio")).toDouble());
    }
    if (overrides.contains(QStringLiteral("maxCumulativeDecodedBytes")))
    {
        limits.maxCumulativeDecodedBytes = static_cast<std::int64_t>(overrides.value(QStringLiteral("maxCumulativeDecodedBytes")).toDouble());
    }
    if (overrides.contains(QStringLiteral("maxRecursiveContentDepth")))
    {
        limits.maxRecursiveContentDepth = static_cast<std::uint32_t>(overrides.value(QStringLiteral("maxRecursiveContentDepth")).toInt());
    }
    if (overrides.contains(QStringLiteral("maxRenderOperations")))
    {
        limits.maxRenderOperations = static_cast<std::uint64_t>(overrides.value(QStringLiteral("maxRenderOperations")).toDouble());
    }
    if (overrides.contains(QStringLiteral("maxObjectDepth")))
    {
        limits.maxObjectDepth = static_cast<std::uint32_t>(overrides.value(QStringLiteral("maxObjectDepth")).toInt());
    }
    if (overrides.contains(QStringLiteral("maxObjectsVisited")))
    {
        limits.maxObjectsVisited = static_cast<std::uint64_t>(overrides.value(QStringLiteral("maxObjectsVisited")).toDouble());
    }
    return limits;
}

// Every fixture tightens exactly one limit (or, for the raster-probe case,
// one check parameter) to the value the corpus test must observe echoed back
// as checks[].budget.limit / the reader's error message.
qint64 expectedLimitFor(const QJsonObject& testCase)
{
    const QJsonObject limitsObject = testCase.value(QStringLiteral("limits")).toObject();
    if (!limitsObject.isEmpty())
    {
        return static_cast<qint64>(limitsObject.constBegin().value().toDouble());
    }

    const QJsonArray checks = testCase.value(QStringLiteral("profile")).toObject().value(QStringLiteral("checks")).toArray();
    if (!checks.isEmpty())
    {
        const QJsonObject check = checks.at(0).toObject();
        if (check.contains(QStringLiteral("max_raster_pixels")))
        {
            return static_cast<qint64>(check.value(QStringLiteral("max_raster_pixels")).toDouble());
        }
    }

    return -1;
}

QByteArray readFixture(const QString& filename)
{
    QFile file(QDir(corpusDir()).filePath(filename));
    if (!file.open(QIODevice::ReadOnly))
    {
        return QByteArray();
    }
    return file.readAll();
}

}   // namespace

class BudgetCorpusTest : public QObject
{
    Q_OBJECT

private slots:
    void initTestCase();

    void sessionBudgetFixturesReportIncomplete_data();
    void sessionBudgetFixturesReportIncomplete();

    void readerBudgetFixturesFailClosed_data();
    void readerBudgetFixturesFailClosed();

    void everyScopedDimensionHasAFixture();

private:
    QJsonArray m_cases;
};

void BudgetCorpusTest::initTestCase()
{
    const QString manifestPath = QDir(corpusDir()).filePath(QStringLiteral("manifest.json"));
    QFile manifestFile(manifestPath);
    QVERIFY2(manifestFile.open(QIODevice::ReadOnly), qPrintable(QStringLiteral("Cannot open manifest '%1'").arg(manifestPath)));

    QJsonParseError parseError;
    const QJsonDocument document = QJsonDocument::fromJson(manifestFile.readAll(), &parseError);
    QVERIFY2(parseError.error == QJsonParseError::NoError, qPrintable(parseError.errorString()));
    QVERIFY2(document.isObject(), "manifest.json must contain a top-level JSON object");

    m_cases = document.object().value(QStringLiteral("cases")).toArray();
    QVERIFY2(!m_cases.isEmpty(), "manifest.json has no fixture cases");
}

void BudgetCorpusTest::sessionBudgetFixturesReportIncomplete_data()
{
    QTest::addColumn<QString>("pdf");
    QTest::addColumn<QJsonObject>("limits");
    QTest::addColumn<QJsonObject>("profile");
    QTest::addColumn<QString>("expectedKind");
    QTest::addColumn<QString>("expectedPool");
    QTest::addColumn<qint64>("expectedLimit");

    for (const QJsonValue& value : m_cases)
    {
        const QJsonObject entry = value.toObject();
        if (entry.value(QStringLiteral("path")).toString() != QStringLiteral("session"))
        {
            continue;
        }

        const QJsonObject expect = entry.value(QStringLiteral("expected")).toObject();
        const QString id = entry.value(QStringLiteral("id")).toString();
        QTest::newRow(qPrintable(id)) << entry.value(QStringLiteral("pdf")).toString()
                                      << entry.value(QStringLiteral("limits")).toObject()
                                      << entry.value(QStringLiteral("profile")).toObject()
                                      << expect.value(QStringLiteral("kind")).toString()
                                      << expect.value(QStringLiteral("pool")).toString()
                                      << expectedLimitFor(entry);
    }
}

void BudgetCorpusTest::sessionBudgetFixturesReportIncomplete()
{
    QFETCH(QString, pdf);
    QFETCH(QJsonObject, limits);
    QFETCH(QJsonObject, profile);
    QFETCH(QString, expectedKind);
    QFETCH(QString, expectedPool);
    QFETCH(qint64, expectedLimit);

    const QByteArray bytes = readFixture(pdf);
    QVERIFY2(!bytes.isEmpty(), qPrintable(QStringLiteral("Cannot read fixture '%1'").arg(pdf)));

    QElapsedTimer timer;
    timer.start();

    // The fixture itself must be an ordinary, fully readable document: the
    // budget under test is the session's, tightened below, not the reader's.
    auto noPassword = [](bool*)
    { return QString(); };
    pdf::PDFDocumentReader reader(nullptr, noPassword, false, false);
    pdf::PDFDocument document = reader.readFromBuffer(bytes);
    QCOMPARE(int(reader.getReadingResult()), int(pdf::PDFDocumentReader::Result::OK));

    pdf::PDFDocumentSession session(&document);
    session.setProcessingLimits(limitsFromOverrides(limits));

    pdf::PreflightEngine engine(&session);
    const pdf::PreflightResult result = engine.run(profile);

    QVERIFY2(timer.elapsed() < BOUNDED_MS, "budget fixture must terminate within the bounded time budget");

    QVERIFY2(!result.inspectionComplete, "a budget-exceeded run must never report a complete inspection");

    const pdf::PreflightVerdict verdict = pdf::reducePreflightVerdict(result);
    QCOMPARE(int(verdict.state), int(pdf::PreflightVerdictState::Incomplete));
    QVERIFY2(!verdict.isPass(), "a budget-exceeded check must never contribute a clean (pass) verdict");

    bool foundExpectedBudget = false;
    for (const pdf::PreflightCheckStatus& status : result.checkStatuses)
    {
        if (status.budgetKind == expectedKind)
        {
            QCOMPARE(status.status, QStringLiteral("incomplete"));
            QCOMPARE(status.reason, QStringLiteral("budget-exceeded"));
            QCOMPARE(status.budgetPool, expectedPool);
            QCOMPARE(status.budgetLimit, expectedLimit);
            QVERIFY2(status.budgetAttempted > status.budgetLimit,
                     "attempted must exceed the configured limit");
            foundExpectedBudget = true;
            break;
        }
    }
    QVERIFY2(foundExpectedBudget,
             qPrintable(QStringLiteral("No check status reported budget kind '%1'").arg(expectedKind)));
}

void BudgetCorpusTest::readerBudgetFixturesFailClosed_data()
{
    QTest::addColumn<QString>("pdf");
    QTest::addColumn<QJsonObject>("limits");
    QTest::addColumn<QString>("expectedKind");
    QTest::addColumn<qint64>("expectedLimit");

    for (const QJsonValue& value : m_cases)
    {
        const QJsonObject entry = value.toObject();
        if (entry.value(QStringLiteral("path")).toString() != QStringLiteral("reader"))
        {
            continue;
        }

        const QJsonObject expect = entry.value(QStringLiteral("expected")).toObject();
        const QString id = entry.value(QStringLiteral("id")).toString();
        QTest::newRow(qPrintable(id)) << entry.value(QStringLiteral("pdf")).toString()
                                      << entry.value(QStringLiteral("limits")).toObject()
                                      << expect.value(QStringLiteral("kind")).toString()
                                      << expectedLimitFor(entry);
    }
}

void BudgetCorpusTest::readerBudgetFixturesFailClosed()
{
    QFETCH(QString, pdf);
    QFETCH(QJsonObject, limits);
    QFETCH(QString, expectedKind);
    QFETCH(qint64, expectedLimit);

    const QByteArray bytes = readFixture(pdf);
    QVERIFY2(!bytes.isEmpty(), qPrintable(QStringLiteral("Cannot read fixture '%1'").arg(pdf)));

    QElapsedTimer timer;
    timer.start();

    auto noPassword = [](bool*)
    { return QString(); };
    pdf::PDFDocumentReader reader(nullptr, noPassword, false, false, limitsFromOverrides(limits));
    pdf::PDFDocument document = reader.readFromBuffer(bytes);
    Q_UNUSED(document);

    QVERIFY2(timer.elapsed() < BOUNDED_MS, "budget fixture must terminate within the bounded time budget");

    // A budget trip while reading must fail the read outright: there is no
    // document yet to report an incomplete inspection about, so failing
    // closed here means the reader refuses to hand back a usable document.
    QCOMPARE(int(reader.getReadingResult()), int(pdf::PDFDocumentReader::Result::Failed));

    const QString message = reader.getErrorMessage();
    QVERIFY2(message.contains(expectedKind), qPrintable(QStringLiteral("Error message '%1' does not name budget kind '%2'").arg(message, expectedKind)));

    // PDFBudgetExceededException's message is "... exceeded: attempted A, limit L (...)."
    // (see PDFBudgetExceededException's constructor in pdfprocessingbudget.cpp);
    // parse it out to confirm the numbers, not just the kind name, are attributable.
    QRegularExpression numbers(QStringLiteral("attempted (\\d+), limit (\\d+)"));
    const QRegularExpressionMatch match = numbers.match(message);
    QVERIFY2(match.hasMatch(), qPrintable(QStringLiteral("Error message '%1' does not carry attempted/limit numbers").arg(message)));
    QCOMPARE(match.captured(2).toLongLong(), expectedLimit);
    QVERIFY2(match.captured(1).toLongLong() > match.captured(2).toLongLong(),
             "attempted must exceed the configured limit");
}

void BudgetCorpusTest::everyScopedDimensionHasAFixture()
{
    // gh-243's scope lists seven adversarial shapes; confirm the manifest
    // still names all seven distinct pdf::PDFBudgetKind values rather than
    // silently losing coverage to a future edit.
    QSet<QString> kinds;
    for (const QJsonValue& value : m_cases)
    {
        kinds.insert(value.toObject().value(QStringLiteral("expected")).toObject().value(QStringLiteral("kind")).toString());
    }

    const QStringList required = {
        QStringLiteral("decompression-ratio"),
        QStringLiteral("cumulative-decoded-bytes"),
        QStringLiteral("recursive-content-depth"),
        QStringLiteral("render-operations"),
        QStringLiteral("render-pixels"),
        QStringLiteral("object-depth"),
        QStringLiteral("objects-visited"),
    };
    for (const QString& kind : required)
    {
        QVERIFY2(kinds.contains(kind), qPrintable(QStringLiteral("No corpus fixture trips budget kind '%1'").arg(kind)));
    }
}

QTEST_MAIN(BudgetCorpusTest)
#include "tst_budgetcorpustest.moc"
